---
title: "R Notebook"
output:
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: console
---

```{r}
library(ggplot2)
#library(scales)
library(tidyr)
library(ggpubr)
setwd('/mnt/c/Users/laura/Documents/EBI_internship/inteql/notebooks/')
```

# Figure 1
```{r}
data <- read.csv('../data/Plotting/figure_1b.csv')
head(data)

p <- ggplot(data, aes(Tissue, Importance, fill=Tissue)) + 
  geom_bar(stat='identity') + 
  coord_flip() + 
  theme_minimal() + 
  scale_y_continuous(labels = scales::comma) + 
  labs(x = '', y = 'Random Forest Importance') + 
  scale_fill_manual(guide=F, values=color.list)

p

ggsave('../figures/figure_1b.png', p, width = 210, height = 140,  units = "mm", dpi = 300)
```


# Figure 2

```{r}
data <- read.csv('../data/Plotting/data_figure2.csv')
head(data)


p <- ggplot(data, aes(RealValue, MeanImputed, color=HowManyTissues)) + 
  geom_point() + 
  theme_minimal() + 
  scale_color_viridis_c(guide_colorbar('Number of tissues')) + 
  geom_abline(color='#92a0ab') + 
  labs(x='Real mean', y='Imputed mean')
p

ggsave('../figures/figure_2.png', p, width = 140, height = 100,  units = "mm", dpi = 300)

```

# Figure 4

```{r}
RMSE_data <- read.csv('../data/Plotting/data_RMSE_figure3.tab', sep='\t')
head(RMSE_data)


rval_data <- read.csv('../data/Plotting/data_rval_figure3.tab', sep='\t')
head(rval_data)

dataE <- tidyr::gather(RMSE_data, key, value, -Tissue, -n_eQTL)
head(dataE)

dataR <- tidyr::gather(rval_data, key, value, -Tissue, -n_eQTL)
head(dataR)
geom_dotplot(aes(color = dose, fill = dose), 
             binaxis='y', stackdir='center')

pE <- ggplot(dataE, aes(key, value, color = n_eQTL, fill=key)) + 
  geom_boxplot() +
  geom_point() +
  labs(x='Imputation Method', y='Root Mean Squared Error') + 
  theme_minimal() + 
  scale_color_viridis_c(guide_colorbar('Number of eQTLs')) + 
  scale_fill_manual(values = c('#92a0ab', '#ffffff', '#ffffff', '#ffffff'), guide=F)

pE

pR <- ggplot(dataR, aes(key, value, color=n_eQTL, fill=key)) + 
  geom_boxplot() +
  geom_point() +
  labs(x='Imputation Method', y='R value') + 
  theme_minimal() + 
  scale_color_viridis_c(guide_colorbar('Number of eQTLs')) + 
  scale_fill_manual(values = c('#92a0ab', '#ffffff', '#ffffff', '#ffffff'), guide=F)
pR


p <- ggpubr::ggarrange(pE, pR,
                    labels = c("A", "B"),
                    ncol = 2, nrow = 1, 
                    common.legend = TRUE, legend = "right")

p
ggsave('../figures/figure_4.png', p,  width = 180, height = 80,  units = "mm", dpi = 300)

```


# Figure 3
```{r}
colors_df <- read.csv('../data/GTEx/Annotations/GTEx_v7_Annotations_ColorTissues.csv', stringsAsFactors = F)
head(colors_df)

color.list <- colors_df$Color
names(color.list) <- colors_df$Tissue_name 
```


# eQTL

```{r}
tissues_id_eqtl <- colnames(read.csv('../data/GTEx/eQTL/GTEx_Analysis_v7_eQTL_allTissues_slope_top_complete.csv.gz'))
tissues_id_eqtl <- tissues_id_eqtl[3:length(tissues_id_eqtl)]
tissues_id_eqtl[48] <- "Cells_EBV-transformed_lymphocytes"
tissues_id_eqtl[18] <- "Brain_Spinal_cord_cervical_c-1"

pc_eqtl <- as.data.frame(readRDS('../objects/GTEx_Analysis_v7_eQTL_allTissues_slope_top_complete_pcsX.rds'))
pc_eqtl$tissue <- tissues_id_eqtl
tail(pc_eqtl)

p <- ggplot(pc_eqtl, aes(PC1, PC2, color=as.factor(tissue))) + 
  geom_point() + 
  theme_minimal() +  
  scale_color_manual(guide=F, values=color.list) + 
  labs(x='Principal Component 1', y='Principal Component 2') 
p 
ggsave('../figures/supplementary_figure_1.png', p)
```


```{r}
D_eqtl <- as.matrix(dist(pc_eqtl[1:2]))
```

# RNA

```{r}
tissues_id_rna <- scan('../data/GTEx/Annotations/GTEx_v7_Annotations_TissuesId.txt', what = 's', sep='\n')
```


```{r}
pc_rna <- as.data.frame(readRDS('../objects/GTEx_Analysis_2016-01-15_v7_RNASeQCv1.1.8_gene_tpm_top_pcsX.rds'))

pc_rna$tissue <- tissues_id_rna
head(pc_rna)
```

```{r}
pc_centroids_rna = read.csv('../data/GTEx/Expression/GTEx_Analysis_2016-01-15_v7_RNASeQCv1.1.8_pc_centroids.csv')
head(pc_centroids_rna)
```


```{r}
head(pc_rna)
p <- ggplot(pc_rna, aes(PC1, PC2, color=as.factor(tissue))) + 
  geom_point() + 
  theme_minimal() +  
  scale_color_manual(guide=F, values=color.list) + 
  labs(x='Principal Component 1', y='Principal Component 2') +
  geom_point(data = pc_centroids_rna, mapping = aes(x, y), color='#000000') + 
  geom_point(data = pc_centroids_rna, mapping = aes(x, y), fill='#000000', shape=4)
p 
#ggsave('../figures/supplementar_figure_2.png', p)
```

```{r}
share_tissues <- intersect(pc_eqtl$tissue, pc_centroids_rna$tissue)
pc_centroids_rna <- pc_centroids_rna[pc_centroids_rna$tissue %in% share_tissues,]
pc_eqtl <- pc_eqtl[pc_eqtl$tissue %in% share_tissues,]
D_eqtl <- as.matrix(dist(pc_eqtl[1:2]))
D_rna <- as.matrix(dist(pc_centroids_rna[2:3]))
```


```{r}
D_rna_df <- as.data.frame(D_rna)
colnames(D_rna_df) <- pc_centroids_rna$tissue
D_rna_df$tissueB <- pc_centroids_rna$tissue
D_rna_df <- tidyr::gather(as.data.frame(D_rna_df), tissueA,  distance_rna, -tissueB)

```

```{r}
D_eqtl_df <- as.data.frame(D_eqtl)
colnames(D_eqtl_df) <- pc_eqtl$tissue
D_eqtl_df$tissueB <-  pc_eqtl$tissue
D_eqtl_df <- tidyr::gather(as.data.frame(D_eqtl_df), tissueA,  distance_eQTL, -tissueB)
```

```{r}
data <- (merge(D_eqtl_df, D_rna_df, by=c('tissueB', 'tissueA')))
```

```{r}
p <- ggplot(data, aes(distance_rna, distance_eQTL)) + 
  geom_point() + 
  theme_minimal() + 
  labs(x = 'RNA expression PCA centroids distance', y='eQTL PCA distance')
p
ggsave('../figures/figure_3.png', p,  width = 80, height = 80,  units = "mm", dpi = 300)
```

```{r}
cor.pc <- cor.test(data$distance_eQTL, data$distance_rna, method = 'pearson')
cor.pc
```



## GTEX LEGENT

```{r}
p <- ggplot(pc_eqtl, aes(PC1, PC2, color=as.factor(tissue))) + 
  geom_point() + 
  theme_minimal() +  
  scale_color_manual(values=color.list, name='') 

l <- ggpubr::get_legend(p)
leg <- ggpubr::as_ggplot(l)

ggsave('../figures/gtex_legend.png', leg)
```


